on:
  push:
    branches:
      - master
name: Deploy Myservice
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Configure AW0S credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn
      - name: Build Site
        run: yarn build
      - name: 'Terraform Init'
        uses: hashicorp/setup-terraform@v1
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'init'
          args:
            -backend-config="bucket=terraform-my-service-state"
            -backend-config="key=terraform-prod.tfstate"
            -backend-config="dynamodb_table=terraform-my-service-state-prod"
            -backend-config="encrypt=true"
      - name: 'Terraform Plan'
        uses: hashicorp/setup-terraform@v1
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'plan'
          args:
            -var="is_temp_env=true"
            -var="env_prefix=prod"
            -var="max_ec2_instances=1"
            -var="min_ec2_instances=1"
            -var="mysql_username=root"
            -var="mysql_password={{ secrets.DB_PASSWORD }}"
      - name: 'Terraform Apply'
        uses: hashicorp/setup-terraform@v1
        with:
          tf_actions_version: 0.14.8
          tf_actions_subcommand: 'apply'
          args: 'tf.plan'
      - name: sync to s3
        run: aws s3 sync public s3://terraform-my-service-state
      - name: invalidate cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths="/*"